MVCStrategyPattern/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCBaseProject.Models;
using MVCStrategyPattern.Models;
using MVCStrategyPattern.Repository;

namespace MVCStrategyPattern.Controllers;

// [Route("[controller]")]
[Authorize]
public class ProductController : Controller
{
    private readonly IProductRepository _productRepository;
    private readonly UserManager<AppUser> _userManager;
    public ProductController(IProductRepository productRepository, UserManager<AppUser> userManager)
    {
        _productRepository = productRepository;
        _userManager = userManager;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var user = await _userManager.FindByNameAsync(User.Identity.Name);
        var userProducts = await _productRepository.GetAllByUserIdAsync(user.Id);
        return View(userProducts);
    }

    // [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    // [HttpGet]
    public async Task<IActionResult> Detail(string id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var product = await _productRepository.GetByIdAsync(id);

        if (product == null)
        {
            return NotFound();
        }
        return View(product);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(string id)
    {
        if (id == null)
            return NotFound();

        var product = await _productRepository.GetByIdAsync(id);

        if (product == null)
            return NotFound();

        return View(product);
    }

    [HttpGet]
    public async Task<IActionResult> Delete(string id)
    {
        if (id == null)
            return NotFound();


        var product = await _productRepository.GetByIdAsync(id);
        if (product == null)
            return NotFound();


        return View(product);
    }

    //-----------------------

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name,Price,Stock,UserId,CreatedAt")] Product product)
    {
        if (product != null)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            product.UserId = user.Id;
            product.CreatedAt = DateTime.Now;
            await _productRepository.CreateAsync(product);

            return RedirectToAction(nameof(Index));
        }

        return View(product);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(string id, Product product)
    {
        if (id != product.Id)
            return NotFound();

        if (ModelState.IsValid)
        {
            try
            {
                await _productRepository.UpdateAsync(product);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ProductExists(product.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(product);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(string id)
    {
        var product = await _productRepository.GetByIdAsync(id);


        await _productRepository.DeleteAsync(product);
        return RedirectToAction(nameof(Index));
    }


    private bool ProductExists(string id)
    {
        return _productRepository.GetByIdAsync(id) != null;
    }




}

MVCStrategyPattern/Controllers/SettingsController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MVCBaseProject.Models;
using MVCStrategyPattern.Models;

namespace MVCStrategyPattern.Controllers;

[Route("[controller]")]
[Authorize]
public class SettingsController : Controller
{
    private readonly UserManager<AppUser> _userManager;
    private readonly SignInManager<AppUser> _signInManager;

    public SettingsController(UserManager<AppUser> userManager, SignInManager<AppUser> ignInManager)
    {
        _userManager = userManager;
        _signInManager = ignInManager;
    }


    public IActionResult Index()
    {
        Settings settings = new();
        var userClaims = User.Claims.Where(c => c.Type == Settings.claimDatabaseType).FirstOrDefault();

        if (userClaims != null)
        {
            settings.DatabaseType = (EDatabaseType)int.Parse(User.Claims.First(c => c.Type == Settings.claimDatabaseType).Value);
        }
        else
        {
            settings.DatabaseType = settings.DefaultDatabaseType;
        }
        return View(settings);
    }

    [HttpPost]
    public async Task<IActionResult> ChangeDatabase(int databaseType)
    {
        var user = await _userManager.FindByNameAsync(User.Identity.Name);
        var newClaim = new Claim(Settings.claimDatabaseType, databaseType.ToString());

        var userClaims = await _userManager.GetClaimsAsync(user);

        var userDatabaseTypeClaim = userClaims.FirstOrDefault(c => c.Type == Settings.claimDatabaseType);

        if (userDatabaseTypeClaim != null)
        {
            await _userManager.ReplaceClaimAsync(user, userDatabaseTypeClaim, newClaim);
        }
        else
        {
            await _userManager.AddClaimAsync(user, newClaim);
        }

        await _signInManager.SignOutAsync();
        userClaims = await _userManager.GetClaimsAsync(user);
        await _signInManager.SignInWithClaimsAsync(user, true, userClaims);

        return RedirectToAction(nameof(Index));
    }



}

MVCStrategyPattern/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCBaseProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCBaseProject.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCBaseProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <div class="dropdown">
                                <a class="btn btn-primary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                    aria-expanded="false">

                                    @User.Identity.Name
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="Product"
                                            asp-action="Index">Products</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="Settings"
                                            asp-action="Index">Settings</a>
                                    </li>

                                    <li> <a class="dropdown-item" asp-controller="Account"
                                            asp-action="Logout"><strong>Logout</strong>
                                        </a></li>

                                </ul>
                            </div>
                        }
                        else
                        {
                            <a asp-controller="Account" asp-action="Login" class="nav-link text-dark">
                                Login</a>
                            @* <button asp-controller="Account" asp-action="Logout" type="submit" class="btn
                        btn-primary">Login</button> *@
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVCBaseProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>